replicaCount: 1

sshpiper:
  loglevel: "info"
  ssh_host_key_base64: ""
  login_grace_time: 30s
  bannertext: ""
  kubernetes_all_namespaces: false
  drop_hostkeys_message: false
  allowed_proxy_addresses: ""
  extraEnvVars: []
  argsOverride: ["--ignore-ip=127.0.0.1"]
  failtoban:
    enabled: false
    max_failures: 3
    ban_duration: 6h

image:
  repository: 11notes/sshpiper
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

rbac:
  create: true
  clusterRole: false

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  runAsNonRoot: true
  runAsGroup: 1000
  runAsUser: 1000

service:
  type: ClusterIP
  port: 22
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}