version: "1.0"
pipes:
- from:
    - username: "sshpiperd"
      authorized_keys: /sshpiperd/var/sshpiperd/authorized_keys
  to:
    host: 192.168.255.1:22
    username: "sshpiperd"
    private_key: /sshpiperd/var/sshpiperd/id_rsa
    ignore_hostkey: true